#include <iostream>
using namespace std;

int main() {
    try {
        int a = 10, b = 0;
        if (b == 0)
            throw runtime_error("除数不能为零!");
        cout << a / b << endl;
    } catch (runtime_error &e) {
        cout << "异常: " << e.what() << endl;
    }
    return 0;
}
